#
# SignService configuration
#

server:
  servlet:
    context-path: /    

signservice:
  domain: localhost
  base-url: http://${signservice.domain}:8080
  default-credential:
    name: SignService
    resource: classpath:signservice.jks
    alias: signservice
    type: JKS
    password: secret
    key-password: secret
  engines:
  - name: "Sandbox"
    processing-paths:
    - /sign/sandbox          
    sign-service-id: https://signservice.digg.se
    client:
      client-id: https://eid2cssp.3xasecurity.com/sign
      certificates:
      - classpath:clients/sandbox.crt
    protocol-handler-bean: "signservice.DssProtocolHandler"  

#
# Logging
#
logging:
  level:
    se:
      swedenconnect:
        security: DEBUG
        signservice: DEBUG
  file:
    path: app/target/logs

#
# Management
#
management:
  auditevents:
    enabled: true
  endpoint:
    auditevents:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "auditevents"

#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
