name: Code coverage

on: [ pull_request ]

jobs:
  build:
    name: Code coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Add code coverage to pull request (core)
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: >-
            ${{ github.workspace }}/core/target/site/jacoco/jacoco.xml,
            ${{ github.workspace }}/protocol/dss-ext11/target/site/jacoco/jacoco.xml
            ${{ github.workspace }}/audit/base/target/site/jacoco/jacoco.xml
            ${{ github.workspace }}/audit/actuator/target/site/jacoco/jacoco.xml
            ${{ github.workspace }}/audit/file/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 60
